### PR TITLE
Remove GFP and Polynomial

### PR DESCRIPTION
**Pull request by slaperche-scality**
They're not necessary for QuadIron

### CODE REVIEW

**Comment by lamphamsy** [comment]
@slaperche-scality : I understand that polynomial and GF::Extension could be removed but why is FEC over GFP removed? In the title, it's GF::Extension, not GFP (prime fields)

**Comment by slaperche-scality** [comment]
@lamphamsy the issue was named "Remove gpfn and polynomial.h" so I though that "gfpn" was GFP, was that wrong?

**Comment by lamphamsy** [comment]
@slaperche-scality : yes, GFP and GFPN are different

**Comment by slaperche-scality** [comment]
@lamphamsy ho, then we should probably revert the last commit of this PR.

What code should be removed to remove GFPN?

**Comment by lamphamsy** [comment]
@slaperche-scality : yes, we should revert it. We have not RS codes for GFPN, I think we have only the GFPN class and its utest.

**Pull request merged**
